version: '3.8'

services:
  p2-form-app:
    build: .
    container_name: p2-form-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
